{spawn, exec, fork}   = require 'child_process'
util                  = require 'util'
path                  = require 'path'

task 'active', 'Watch source files, build JS, and reload browser', (options) ->
  server = fork (__dirname + '/server.js'), null,
    env:
      activeReload: true

  runCommand = (name, args...) ->
    proc =           spawn name, args

    proc.stderr.on   'data', (buffer) -> 
      message = buffer.toString()
      console.log message
      server.send 
        source: 'compiler'
        type: 'stderr'
        message: message    

    proc.stdout.on   'data', (buffer) -> 
      message = buffer.toString()
      console.log message
      server.send 
        source: 'compiler'
        type: 'stdout'
        message: message
        
    proc.on 'exit', (status) -> process.exit(1) if status isnt 0
    proc
  
  coffee_path = "#{process.cwd()}/node_modules/coffee-script/bin/coffee"

  fs.exists coffee_path, (exists) ->
    if exists
      compiler = runCommand coffee_path, '-wc', './public'

      process.on 'exit', ->
        compiler.kill()
        server.kill()
    else
      console.log "Coffee not found. Run from a Coolkit project directory."